from .base.enum import BaseEnum, BaseIntEnum


class DeleteStatus(BaseEnum):
    ALL = "all"
    DELETED = "deleted"
    NOT_DELETED = "not_deleted"


class Status(BaseIntEnum):
    ACTIVE = 1
    INACTIVE = 0


class PaymentStatus(BaseIntEnum):
    PENDING = 0
    ACCEPTED = 1
    REJECTED = 2


class UserType(BaseIntEnum):
    TEACHER = 1
    STUDENT = 0


class OsType(BaseIntEnum):
    ANDROID = 1
    IOS = 2
    WEB = 3
    WINDOWS = 4
    LINUX = 5
    MAC = 6


class Gender(BaseIntEnum):
    MALE = 1
    FEMALE = 2


class NotificationObjectType(BaseIntEnum):
    ALERT = 1
    MARKETING = 2
    PROMOTION = 3
    SPECIAL_DEAL = 4
    FEEDBACK = 5
    PROVIDER = 6
    CUSTOMER = 7
    SERVICE_PROVIDER = 8
    SERVICE = 9
    SERVICE_SCHEDULE = 10
    HOUSE = 11
    RESERVATION = 12
    RESERVATION_DETAIL = 13
    RESERVATION_QR = 14
    CUSTOMER_INVOICE = 15
    PROVIDER_INVOICE = 16
    SERVICE_PROVIDER_INVOICE = 17
    COMFERYA_INVOICE = 18
    TRANSACTION = 19
    STORY = 20
    CHAT = 21


class NotificationTemplateType(BaseIntEnum):
    NEW_PROVIDER = 1
    ACCEPTED_PROVIDER = 2
    REJECTED_PROVIDER = 3
    NEW_CUSTOMER = 4
    ACCEPTED_CUSTOMER = 5
    REJECTED_CUSTOMER = 6
    NEW_HOUSE = 7
    ACCEPTED_HOUSE = 8
    REJECTED_HOUSE = 9
    BEST_DEAL_HOUSE = 10
    NEW_HOUSE_REVIEW = 11
    RESERVATION_CONFLICT_NEED_REFUND = 12
    RESERVATION_ACCEPTED_FOR_PROVIDER = 13
    RESERVATION_ACCEPTED_FOR_CUSTOMER = 14
    RESERVATION_NEED_RETURN_DEPOSIT = 15
    NEW_SERVICE_SCHEDULE = 16
    UPDATE_SERVICE_SCHEDULE = 17
    DELETE_SERVICE_SCHEDULE = 18
    COMPLETE_SERVICE_SCHEDULE = 19
    SERVICE_PROVIDER_INVOICE_NEED_ACTION = 20
    NEW_FEEDBACK = 21
    BEFORE_CHECK_IN = 22
    BEFORE_CHECKOUT = 23
    CHECK_IN_QR_SCAN = 24
    NEED_SCHEDULING_SERVICES_FOR_CUSTOMER = 25
    NEED_SCHEDULING_SERVICES_FOR_SERVICE_PROVIDER = 26
    NEED_SCHEDULING_EARLY_USAGE_SERVICES_FOR_CUSTOMER = 27
    NEED_SCHEDULING_EARLY_USAGE_SERVICES_FOR_SERVICE_PROVIDER = 28
