# Generated by Django 4.2.17 on 2025-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_historicalcoupon_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcoupon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcoupon',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcoupon',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='historicalordercourse',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordercourse',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='HistoricalCoupon',
        ),
    ]
