# Generated by Django 4.2.17 on 2025-02-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalcoupon_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordercourse',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='ordercourse',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
