# Generated by Django 4.2.17 on 2025-03-06 08:28

import common.model_fields.decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_historicalordercourse_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='coupon_percentage',
            field=common.model_fields.decimal.PercentageField(blank=True, null=True, validators=[]),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_percentage',
            field=common.model_fields.decimal.PercentageField(blank=True, null=True, validators=[]),
        ),
    ]
