# Generated by Django 4.2.17 on 2025-01-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='url',
            field=models.TextField(max_length=100),
        ),
    ]
