# Generated by Django 4.2.17 on 2025-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_file_url_alter_historicalfile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/files/'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/files/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/videos/'),
        ),
    ]
