# Generated by Django 4.2.17 on 2025-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_question_historicalquiz_historicalquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquiz',
            name='info_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='info_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquiz',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
