# Generated by Django 4.2.17 on 2025-02-04 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_course_favourite_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='favourite_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
