# Generated by Django 4.2.17 on 2025-01-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_about_historicaluser_device_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluniveristy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical univeristy', 'verbose_name_plural': 'historical Univeristies'},
        ),
        migrations.AlterModelOptions(
            name='univeristy',
            options={'verbose_name_plural': 'Univeristies'},
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='city',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalexperience',
            old_name='city',
            new_name='user',
        ),
    ]
