# Generated by Django 4.2.17 on 2025-01-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluniveristy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
