# Generated by Django 4.2.17 on 2025-01-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_historicaluniveristy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluniveristy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical univeristy', 'verbose_name_plural': 'historical Univeristies'},
        ),
        migrations.AlterModelOptions(
            name='univeristy',
            options={'verbose_name_plural': 'Univeristies'},
        ),
    ]
