# Generated by Django 4.2.17 on 2025-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_historicaluser_full_name_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='device_id',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
