# Generated by Django 5.0.10 on 2025-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_item_created_by_alter_item_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='file',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
